-- Create the Referrals table
create table public.referrals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  referrer_id bigint references public.profiles(telegram_id) not null,
  referee_id bigint references public.profiles(telegram_id) not null,
  
  -- Prevent duplicate referrals (Unique constraint on referee)
  constraint referrals_referee_id_key unique (referee_id),
  -- Prevent self-referral
  constraint referrals_no_self_referral check (referrer_id <> referee_id)
);

-- Enable RLS
alter table public.referrals enable row level security;

-- Policy: Anyone can read their own referrals (as referrer)
create policy "Users can view recruits"
  on public.referrals for select
  using ( auth.uid() = referrer_id );

-- Policy: Service Role (Admin) has full access (Implicit, but good to know)
-- No insert policy needed for public because we use Service Role Bypass in API.
